data:
    name: 'coco'
    cache_in_memory: false
    validation_size: 96
    labels: magic-point_coco-export1  # use your own labels here
    preprocessing:
        blur_size: 21
        resize: [480, 640]  # Should be multiples of 8
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false  # not implemented
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true
        valid_border_margin: 3
    batch_size: 1
model:
    name: 'super_point'
    input_size: [480, 640]
    batch_size: 1
    eval_batch_size: 1
    learning_rate: 0.0001
    lambda_d: 0.05
    positive_margin: 1
    negative_margin: 0.2
    lambda_loss: 10000
    detection_threshold: 0.001
    nms: 4
    top_k: 600
    initializerPaths: 
        hourgrlass: 'D:/projects/SP2/weights_hourglass.npy'
        PSP_net50:  'D:/projects/SP2/weights_psp_net50.npy'
    training: true
train_iter: 600000
validation_interval: 5000